[build-system]
requires=["flit_core >=3.2,<4"]
build-backend="flit_core.buildapi"

[project]
name="PMM Docs"
authors=[{name="MiniDeth3",email="Larsbyerly11223@gmail.com"}]
dynamic=["version","description"]